import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="w-full h-screen bg-sky-50 flex items-center justify-center">
            {children}
        </div>
    );
}
